// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * KeyItem 表示一个密钥项
 */
export class KeyItem {
    "id": string;
    "name": string;
    "type": string;
    "value": string;
    "description": string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new KeyItem instance. */
    constructor($$source: Partial<KeyItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyItem instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyItem($$parsedSource as Partial<KeyItem>);
    }
}
