// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KeyService 提供密钥管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddKey 添加新密钥
 */
export function AddKey(item: $models.KeyItem): $CancellablePromise<$models.KeyItem> {
    return $Call.ByID(2900473383, item).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteKey 删除密钥
 */
export function DeleteKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(2793011373, id);
}

/**
 * GetAllKeys 获取所有密钥
 */
export function GetAllKeys(): $CancellablePromise<$models.KeyItem[]> {
    return $Call.ByID(2705514250).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveKeys 保存所有密钥
 */
export function SaveKeys(keys: $models.KeyItem[]): $CancellablePromise<void> {
    return $Call.ByID(1803700672, keys);
}

/**
 * UpdateKey 更新密钥
 */
export function UpdateKey(item: $models.KeyItem): $CancellablePromise<$models.KeyItem> {
    return $Call.ByID(1821894111, item).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.KeyItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
